export const siteMetadata = {
  title: 'CodeBlog',
  author: 'zanak',
  headerTitle: 'Next.js Blog',
  description: 'A blog created with Next.js, Tailwind.css and contentlayer.',
  language: 'en-us',
  theme: 'system',
  siteUrl: 'https://github-landingpage.vercel.app/',
  siteLogo: '/logo.png',
  socialBanner: '/social-banner.png',
  email: 'johndoe@gmail.com',
  github: 'https://github.com',
  twitter: 'https://twitter.com',
  facebook: 'https://facebook.com',
  youtube: 'https://youtube.com',
  linkedin: 'https://www.linkedin.com',
  dribbble: 'https://www.dribbble.com',
  locale: 'en-US',
};
